// Code generated by "stringer -linecomment -output codec\hevc\strings.go --type NALUType codec\hevc\nal.go"; DO NOT EDIT.

package hevc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NALUTypeInvalid-0]
	_ = x[NALUTypeHVCC-1]
	_ = x[NALUTypeAnnexB-2]
}

const _NALUType_name = "InvalidHVCCAnnexB"

var _NALUType_index = [...]uint8{0, 7, 11, 17}

func (i NALUType) String() string {
	if i < 0 || i >= NALUType(len(_NALUType_index)-1) {
		return "NALUType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NALUType_name[_NALUType_index[i]:_NALUType_index[i+1]]
}
