// Code generated by "stringer"; DO NOT EDIT.

package flv

var TagTypeMap = map[byte]string{
	TagAudio:  "TagAudio",
	TagVideo:  "TagVideo",
	TagScript: "TagScript",
}

var VideoFormatTypeMap = map[byte]string{
	VideoKeyFrame:             "VideoKeyFrame",
	VideoInterFrame:           "VideoInterFrame",
	VideoDisposableInterFrame: "VideoDisposableInterFrame",
	VideoGeneratedKeyFrame:    "VideoGeneratedKeyFrame",
	VideoInfoFrame:            "VideoInfoFrame",
}

var VideoCodecIDMap = map[byte]string{
	VideoJPEG:            "VideoJPEG",
	VideoH263:            "VideoH263",
	VideoScreenVideo:     "VideoScreenVideo",
	VideoOn2VP6:          "VideoOn2VP6",
	VideoOn2VP6WithAlpha: "VideoOn2VP6WithAlpha",
	VideoScreenVideoV2:   "VideoScreenVideoV2",
	VideoH264:            "VideoH264",
}

var AudioSoundFormatMap = map[byte]string{
	AudioLinearPCM:           "AudioLinearPCM",
	AudioADPCM:               "AudioADPCM",
	AudioMP3:                 "AudioMP3",
	AudioPCM:                 "AudioPCM",
	AudioNellymoser16KHzMono: "AudioNellymoser16KHzMono",
	AudioNellymoser8KHzMono:  "AudioNellymoser8KHzMono",
	AudioNellymoser:          "AudioNellymoser",
	AudioG711A:               "AudioG711A",
	AudioG711U:               "AudioG711U",
	AudioAAC:                 "AudioAAC",
	AudioSpeex:               "AudioSpeex",
	AudioMP38KHz:             "AudioMP38KHz",
	AudioDeviceSpecificSound: "AudioDeviceSpecificSound",
}

var AudioSoundRateMap = map[byte]string{
	Audio5KHz:  "Audio5KHz",
	Audio11KHz: "Audio11KHz",
	Audio22KHz: "Audio22KHz",
	Audio44KHz: "Audio44KHz",
}

var AudioSoundSizeMap = map[byte]string{
	Audio8bit:  "Audio8bit",
	Audio16bit: "Audio16bit",
}

var AudioSoundTypeMap = map[byte]string{
	AudioMono:   "AudioMono",
	AudioStereo: "AudioStereo",
}
